const carBrands: string[] = [
  'Acura',
  'Aston Martin',
  'Audi',
  'Porshe',
  'Tesla',
  'Mersedes',
  'BMW',
  'Toyota',
  'Dodge',
  'Opel',
  'Renault',
  'Ford',
  'Mazda',
  'Mitsubishi',
  'Lexus',
  'Ferrari',
  'Porsche',
  'Hyundai',
  'Subaru',
  'Infinity',
  'Nissan',
  'Chevrolet',
  'Chrysler',
  'Citroen',
  'Honda',
  'Fiat',
  'Jaguar',
  'Lamborghini',
  'McLaren',
  'Lotus',
];
const carModels: string[] = [
  'Cybertruck',
  'ES',
  'LS',
  'RX',
  'GX',
  'LX',
  'Model S',
  'RSX-S',
  'DB11',
  'Camry',
  'Corsa',
  'Cayenne',
  'A7',
  'A8',
  '911 Carrera S',
  'Impreza',
  'WRX',
  'M2',
  'M5',
  'TT',
  'Gallardo',
  'Aventador',
  '911 Turbo',
  'Cayenne',
  'Corolla',
  'Camaro SS',
  'Corvette',
  'Challenger',
  'Charger',
  'RX-7',
  'AMG GT',
  'Cayman GT4',
  '350Z',
  'Impreza WRX STI',
  'GT',
  'Lancer Evolution',
  'F-Type R',
  'MX-5',
  'S2000',
  'Aventador',
  'Mustang',
  'Diablo',
  'Huracan',
  'Murcielago',
  'Roadster',
  'Enzo',
  'E-tron',
  'S7',
  'I8',
  'X3',
];

export default function createRandomName(): string {
  // const randomBrand: number = Math.floor(Math.random() * carBrands.length);
  const randomBrand: number = Math.floor(Math.random() * carBrands.length);
  const randomModel: number = Math.floor(Math.random() * carModels.length);
  return `${carBrands[randomBrand]} ${carModels[randomModel]}`;
}
